distance_type: Tanimoto
embedding_type: EStateFingerprint
prunning: false
query_path: /home/haowei/Desktop/repos/DRR/benchmarks/crossdocked/ligand_smiles.txt
save_path: /home/haowei/Desktop/repos/DRR/benchmarks/crossdocked/retrieve
topk: 5
